# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contractors', '0001_initial'),
        ('employees', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workorder_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Work Order ID')),
                ('title', models.CharField(max_length=255, verbose_name='Work Order Title / Summary')),
                ('description', models.TextField(verbose_name='Scope of Work & Technical Instructions')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Emergency Dispatch')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Estimated Cost ($)')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Actual Incurred Cost ($)')),
                ('due_date', models.DateField(verbose_name='Target Completion Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('status', models.CharField(choices=[('CREATED', 'Created / Ticket Opened'), ('ASSIGNED', 'Assigned to Crew / Vendor'), ('SCHEDULED', 'Scheduled in Field Calendar'), ('IN_PROGRESS', 'In Progress / Field Execution'), ('WAITING', 'Waiting for Parts / Permitting'), ('COMPLETED', 'Completed & Ready for Inspection'), ('CANCELLED', 'Cancelled / Aborted')], db_index=True, default='CREATED', max_length=50, verbose_name='Execution Status')),
                ('is_safety_briefed', models.BooleanField(default=True, verbose_name='Safety Tailgate Briefing Verified')),
                ('client_signoff', models.CharField(blank=True, max_length=150, verbose_name='Client / Inspector Sign-Off Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='assets.asset', verbose_name='Target Asset')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='employees.employee', verbose_name='Assigned Field Engineer / Lead')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='contractors.contractor', verbose_name='Contractor Vendor (If Out-sourced)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='locations.location', verbose_name='Field Site Location')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('hours_spent', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('technician_name', models.CharField(blank=True, max_length=150)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Task',
                'verbose_name_plural': 'Work Order Tasks',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['workorder_id'], name='workorders__workord_7d3a86_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='workorders__status_a1b0ea_idx'),
        ),
    ]
