# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Project Reference ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Scope & Objectives')),
                ('start_date', models.DateField(verbose_name='Commencement Date')),
                ('end_date', models.DateField(verbose_name='Target Completion Date')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Approved Project Budget ($)')),
                ('actual_spending', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Cumulative Spending ($)')),
                ('progress', models.IntegerField(default=0, verbose_name='Overall Progress Percentage (0–100%)')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning & Feasibility'), ('APPROVED', 'Approved / Funding Allocated'), ('ACTIVE', 'Active Construction / Execution'), ('DELAYED', 'Delayed / Schedule Variance'), ('COMPLETED', 'Completed & Handed Over'), ('CANCELLED', 'Cancelled / De-scoped')], db_index=True, default='PLANNING', max_length=50, verbose_name='Project Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contractors.contractor', verbose_name='Prime Contractor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='Owner Agency')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Lead Project Manager')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Capital Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_title', models.CharField(max_length=255, verbose_name='Milestone Title')),
                ('due_date', models.DateField(verbose_name='Milestone Due Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Milestone Achieved')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('weight_percentage', models.IntegerField(default=20, verbose_name='Weight / Contribution (%)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Parent Project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='projects_pr_project_38fe3b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-start_date'], name='projects_pr_status_bf6304_idx'),
        ),
    ]
