# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_code', models.CharField(max_length=50, unique=True, verbose_name='Equipment Serial Tag')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='Equipment Unit Name')),
                ('equipment_type', models.CharField(choices=[('HVAC_CHILLER', 'HVAC Central Chiller / AHU'), ('ELEVATOR_LIFT', 'Passenger / Freight Elevator'), ('DIESEL_GENERATOR', 'Emergency Diesel Generator'), ('ELECTRICAL_TRANSFORMER', 'Substation Transformer & Switchgear'), ('PLUMBING_PUMP', 'Water Pressure Booster Pump Station'), ('FIRE_SUPPRESSION', 'Fire Sprinkler & Deluge System'), ('SECURITY_CCTV', 'Access Control & CCTV Surveillance'), ('SOLAR_INVERTER', 'Solar Photovoltaic Inverter'), ('BOILER', 'High Pressure Steam Boiler'), ('OTHER', 'General Facility Asset')], default='HVAC_CHILLER', max_length=50, verbose_name='Equipment Classification')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Original Manufacturer')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model / Part Number')),
                ('power_rating_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Power Rating (kW / kVA)')),
                ('operating_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=9, verbose_name='Cumulative Run Hours')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Last Serviced Date')),
                ('next_service_due', models.DateField(blank=True, null=True, verbose_name='Next Service Due Date')),
                ('service_contract_vendor', models.CharField(blank=True, max_length=200, verbose_name='SLA Service Vendor')),
                ('telemetry_data', models.JSONField(blank=True, default=dict, verbose_name='Sensor Telemetry Readings')),
                ('notes', models.TextField(blank=True, verbose_name='Maintenance Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_extension', to='assets.asset', verbose_name='Central Asset Record')),
            ],
            options={
                'verbose_name': 'Facility Equipment',
                'verbose_name_plural': 'Facility Equipment & MEP',
                'ordering': ['equipment_code'],
            },
        ),
        migrations.CreateModel(
            name='FacilityServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('PREVENTIVE_MAINTENANCE', 'Scheduled Preventive Service'), ('EMERGENCY_REPAIR', 'Emergency Breakdown Repair'), ('PARTS_REPLACEMENT', 'Component / Filter Replacement'), ('ANNUAL_OVERHAUL', 'Comprehensive Annual Overhaul'), ('SAFETY_INSPECTION', 'Compliance & Safety Audit')], default='PREVENTIVE_MAINTENANCE', max_length=50)),
                ('technician_name', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('operating_hours_at_service', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='facilities.facilityequipment')),
            ],
            options={
                'verbose_name': 'Facility Service Log',
                'verbose_name_plural': 'Facility Service Logs',
                'ordering': ['-service_date'],
            },
        ),
    ]
