# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Browser User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Timestamp')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Timestamp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session Active')),
            ],
            options={
                'verbose_name': 'User Login Session',
                'verbose_name_plural': 'User Login Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Matrix Theme (Default)'), ('light', 'Clean Enterprise Light'), ('high_contrast', 'High Contrast Mode')], default='dark', max_length=20, verbose_name='UI Color Theme')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Receive Email Notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Receive SMS Notifications')),
                ('compact_tables', models.BooleanField(default=False, verbose_name='Compact Data Tables')),
                ('bio', models.TextField(blank=True, verbose_name='Professional Bio')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Office Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('organization_admin', 'Organization Admin'), ('infrastructure_manager', 'Infrastructure Manager'), ('asset_manager', 'Asset Manager'), ('project_manager', 'Project Manager'), ('maintenance_manager', 'Maintenance Manager'), ('inspector', 'Inspector'), ('field_engineer', 'Field Engineer'), ('contractor_manager', 'Contractor Manager'), ('finance_manager', 'Finance Manager'), ('support_agent', 'Support Agent'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=50, verbose_name='Enterprise Role')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Official Job Title')),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee / Badge ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Profile Picture')),
                ('is_two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Security Enabled')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Administrative Notes')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
