# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Inspection Reference ID')),
                ('inspection_type', models.CharField(choices=[('ROUTINE', 'Routine Cyclic Inspection'), ('SAFETY', 'Safety & Hazard Compliance Audit'), ('STRUCTURAL', 'Detailed Non-Destructive Structural Assessment'), ('PREVENTIVE', 'Pre-Maintenance Diagnostic Inspection'), ('EMERGENCY', 'Post-Disaster / Emergency Damage Assessment')], default='ROUTINE', max_length=50, verbose_name='Inspection Classification')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('condition_score', models.IntegerField(default=80, verbose_name='Assessed Condition Score (0–100)')),
                ('findings', models.TextField(verbose_name='Observed Physical Findings & Defect Notes')),
                ('recommendations', models.TextField(blank=True, verbose_name='Engineering Recommendations / Remedial Actions')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled / Pending Dispatch'), ('IN_PROGRESS', 'In Progress (Field Survey)'), ('COMPLETED', 'Completed & Submitted'), ('REVIEWED', 'Reviewed & Approved by Engineer'), ('REJECTED', 'Rejected / Re-Audit Required')], db_index=True, default='SCHEDULED', max_length=50, verbose_name='Inspection Status')),
                ('weather_conditions', models.CharField(blank=True, max_length=150, verbose_name='Ambient Weather Conditions')),
                ('photo_primary', models.ImageField(blank=True, null=True, upload_to='inspections/%Y/%m/', verbose_name='Primary Photo Evidence')),
                ('photo_secondary', models.ImageField(blank=True, null=True, upload_to='inspections/%Y/%m/', verbose_name='Secondary Photo Evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='assets.asset', verbose_name='Inspected Infrastructure Asset')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Lead Inspector / Field Engineer')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=255, verbose_name='Inspection Check Item')),
                ('is_satisfactory', models.BooleanField(default=True, verbose_name='Satisfactory / Pass')),
                ('score_1_to_10', models.IntegerField(default=8, verbose_name='Rating (1-10)')),
                ('comments', models.TextField(blank=True, verbose_name='Inspector Comments')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inspections.inspection', verbose_name='Inspection')),
            ],
            options={
                'verbose_name': 'Inspection Checklist Item',
                'verbose_name_plural': 'Inspection Checklist Items',
                'ordering': ['item_title'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_id'], name='inspections_inspect_ba2d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status', '-inspection_date'], name='inspections_status_b45976_idx'),
        ),
    ]
