# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Location Site Name')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Location GIS Code')),
                ('country', models.CharField(default='United States', max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State / Province')),
                ('city', models.CharField(max_length=100, verbose_name='City / Municipality')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District / County')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Operational Zone')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='Subdivision / Ward / Area')),
                ('address', models.TextField(verbose_name='Full Physical Street Address')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='Postal / ZIP Code')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude Coordinate')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude Coordinate')),
                ('elevation_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Elevation (Meters)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Geospatial Location',
                'verbose_name_plural': 'Geospatial Locations',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'district'], name='locations_l_city_518002_idx'), models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx')],
            },
        ),
    ]
