# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('road_code', models.CharField(max_length=50, unique=True, verbose_name='Official Road Code (e.g. US-101-S)')),
                ('road_name', models.CharField(max_length=255, verbose_name='Corridor / Street Name')),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Length (Kilometers)')),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Width (Meters)')),
                ('lanes_count', models.IntegerField(default=2, verbose_name='Number of Traffic Lanes')),
                ('surface_type', models.CharField(choices=[('ASPHALT', 'Asphalt Pavement'), ('CONCRETE', 'Portland Cement Concrete'), ('GRAVEL', 'Gravel / Unpaved'), ('COMPOSITE', 'Composite Pavement'), ('BRICK_PAVER', 'Interlocking Paver Blocks'), ('OTHER', 'Other Surface')], default='ASPHALT', max_length=50, verbose_name='Surface Pavement Type')),
                ('construction_date', models.DateField(blank=True, null=True, verbose_name='Original Construction Date')),
                ('last_resurfaced_date', models.DateField(blank=True, null=True, verbose_name='Last Resurfacing / Overlay Date')),
                ('traffic_level', models.CharField(choices=[('LOW', 'Low (< 2,000 AADT)'), ('MEDIUM', 'Medium (2,000 - 10,000 AADT)'), ('HIGH', 'High (10,000 - 40,000 AADT)'), ('VERY_HIGH', 'Very High (40,000 - 100,000 AADT)'), ('CONGESTED', 'Severe Congestion (> 100,000 AADT)')], default='MEDIUM', max_length=50, verbose_name='Average Daily Traffic Level')),
                ('speed_limit_mph', models.IntegerField(default=55, verbose_name='Posted Speed Limit (mph)')),
                ('pci_score', models.IntegerField(default=85, verbose_name='Pavement Condition Index (PCI 0–100)')),
                ('notes', models.TextField(blank=True, verbose_name='Engineering Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_extension', to='assets.asset', verbose_name='Central Asset Record')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roads', to='organizations.region', verbose_name='Administrative Region')),
            ],
            options={
                'verbose_name': 'Road Network',
                'verbose_name_plural': 'Road Networks',
                'ordering': ['road_code'],
            },
        ),
        migrations.CreateModel(
            name='RoadDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('POTHOLE', 'Pothole / Surface Cavity'), ('ALLIGATOR_CRACKING', 'Alligator / Fatigue Cracking'), ('LONGITUDINAL_CRACK', 'Longitudinal / Transverse Crack'), ('RUTTING', 'Wheel Path Rutting'), ('RAVELING', 'Raveling / Aggregate Loss'), ('DRAINAGE_ISSUE', 'Culvert / Drainage Blockage'), ('SUBSIDENCE', 'Subgrade Settlement / Sinkhole'), ('GUARDRAIL_DAMAGE', 'Guardrail / Barrier Impact Damage')], max_length=50, verbose_name='Defect Type')),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Hazard')], default='MEDIUM', max_length=20)),
                ('chainage_km', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Chainage / Mile Marker (km)')),
                ('description', models.TextField(verbose_name='Defect Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defects/roads/%Y/%m/')),
                ('is_repaired', models.BooleanField(default=False)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='roads.road', verbose_name='Road Corridor')),
            ],
            options={
                'verbose_name': 'Road Defect',
                'verbose_name_plural': 'Road Defects',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='RoadRepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_title', models.CharField(max_length=255)),
                ('repair_type', models.CharField(default='Milling & Resurfacing', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField()),
                ('pci_gain', models.IntegerField(default=15, verbose_name='PCI Score Improvement (+Points)')),
                ('summary', models.TextField(blank=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='roads.road')),
            ],
            options={
                'verbose_name': 'Road Repair History',
                'verbose_name_plural': 'Road Repair Records',
                'ordering': ['-completion_date'],
            },
        ),
    ]
