# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteriorationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('ROAD', 'Road / Highway Segment'), ('BRIDGE', 'Bridge / Overpass'), ('BUILDING', 'Building / Structure'), ('FACILITY', 'Facility / MEP Plant'), ('STREET_INFRA', 'Street & Traffic Infrastructure'), ('UTILITY', 'Power / Electrical Utility'), ('WATER', 'Water & Drainage Asset'), ('HEAVY_EQUIPMENT', 'Heavy Machinery & Fleet')], max_length=50, unique=True, verbose_name='Asset Classification')),
                ('expected_lifecycle_years', models.IntegerField(default=30)),
                ('annual_decay_rate_pct', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Baseline Annual Degradation Rate (%)')),
                ('heavy_load_multiplier', models.DecimalField(decimal_places=2, default=1.35, max_digits=4, verbose_name='High Traffic / Heavy Load Factor')),
                ('severe_climate_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4, verbose_name='Harsh Climate / Freeze-Thaw Factor')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Deterioration Model',
                'verbose_name_plural': 'Deterioration Models',
            },
        ),
        migrations.CreateModel(
            name='ConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(verbose_name='Assessment Date')),
                ('condition_score', models.IntegerField(verbose_name='Overall Health Score (0-100)')),
                ('condition_category', models.CharField(choices=[('EXCELLENT', 'Excellent (90-100)'), ('GOOD', 'Good (70-89)'), ('FAIR', 'Fair (50-69)'), ('POOR', 'Poor (25-49)'), ('CRITICAL', 'Critical (0-24)')], default='GOOD', max_length=50)),
                ('structural_index', models.IntegerField(default=80, verbose_name='Structural Integrity Index (0-100)')),
                ('operational_index', models.IntegerField(default=85, verbose_name='Operational Reliability Index (0-100)')),
                ('safety_index', models.IntegerField(default=90, verbose_name='Public Safety Index (0-100)')),
                ('notes', models.TextField(blank=True, verbose_name='Assessment Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lead Assessor')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_logs', to='assets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Condition Log',
                'verbose_name_plural': 'Condition Logs',
                'ordering': ['-recorded_date', '-created_at'],
                'indexes': [models.Index(fields=['asset', '-recorded_date'], name='conditions__asset_i_dcc3d4_idx'), models.Index(fields=['condition_category'], name='conditions__conditi_9eb207_idx')],
            },
        ),
    ]
