# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contractors', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Maintenance Code ID')),
                ('title', models.CharField(max_length=255, verbose_name='Maintenance Job Title')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Cyclic Maintenance'), ('CORRECTIVE', 'Corrective / Defect Repair'), ('EMERGENCY', 'Emergency Breakdown Intervention'), ('PREDICTIVE', 'Condition-Based Predictive Overhaul')], default='PREVENTIVE', max_length=50, verbose_name='Maintenance Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Emergency')], default='MEDIUM', max_length=20, verbose_name='Priority Level')),
                ('start_date', models.DateField(verbose_name='Scheduled Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=6, verbose_name='Est. Labor Hours')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Maintenance Cost ($)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned / Draft'), ('SCHEDULED', 'Scheduled Dispatch'), ('IN_PROGRESS', 'In Progress (Active Work)'), ('ON_HOLD', 'On Hold (Awaiting Spares/Weather)'), ('COMPLETED', 'Completed & Commissioned'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=50)),
                ('trigger_condition', models.CharField(blank=True, max_length=200, verbose_name='Maintenance Trigger / Threshold')),
                ('procedure_notes', models.TextField(blank=True, verbose_name='Standard Operating Procedure Checklist')),
                ('notes', models.TextField(blank=True, verbose_name='Execution Notes & Findings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset', verbose_name='Target Infrastructure Asset')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='organizations.team', verbose_name='Internal Operations Crew / Team')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_contracts', to='contractors.contractor', verbose_name='External Contractor Vendor')),
            ],
            options={
                'verbose_name': 'Maintenance Plan',
                'verbose_name_plural': 'Maintenance Plans & Jobs',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.CharField(max_length=255, verbose_name='Task Step Completed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parts_replaced', models.CharField(blank=True, max_length=255, verbose_name='Parts / Spares Replaced')),
                ('notes', models.TextField(blank=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technician')),
                ('maintenance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='maintenance.maintenanceplan', verbose_name='Maintenance Job')),
            ],
            options={
                'verbose_name': 'Maintenance Action Log',
                'verbose_name_plural': 'Maintenance Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['maintenance_code'], name='maintenance_mainten_18b33c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_9c8202_idx'),
        ),
    ]
