# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_id_code', models.CharField(max_length=50, unique=True, verbose_name='Building ID Code')),
                ('building_name', models.CharField(max_length=255, verbose_name='Building Name')),
                ('building_type', models.CharField(choices=[('OFFICE', 'Administrative / Headquarters Office'), ('SCHOOL', 'Educational / School / University'), ('HOSPITAL', 'Healthcare / Hospital / Clinic'), ('WAREHOUSE', 'Warehouse / Logistics Depot'), ('GOVERNMENT', 'Government / Civic Center / Courthouse'), ('EMERGENCY_SERVICES', 'Fire Station / Police Depot / EMS'), ('TRANSIT_TERMINAL', 'Transit Station / Airport Terminal'), ('RESIDENTIAL', 'Public / Municipal Housing'), ('COMMERCIAL', 'Commercial Facility'), ('OTHER', 'Other Structure')], default='OFFICE', max_length=50, verbose_name='Building Classification')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('floor_count', models.IntegerField(default=1, verbose_name='Number of Floors')),
                ('total_area_sqft', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Gross Floor Area (sq ft)')),
                ('construction_year', models.IntegerField(verbose_name='Year Built')),
                ('occupancy_capacity', models.IntegerField(default=100, verbose_name='Maximum Occupancy Capacity')),
                ('energy_rating', models.CharField(choices=[('LEED_PLATINUM', 'LEED Platinum'), ('LEED_GOLD', 'LEED Gold'), ('LEED_SILVER', 'LEED Silver'), ('ENERGY_STAR', 'Energy Star Certified'), ('STANDARD', 'Standard Municipal Code')], default='STANDARD', max_length=50, verbose_name='Energy & Sustainability Rating')),
                ('is_fire_safety_certified', models.BooleanField(default=True, verbose_name='Fire & Life Safety Certified')),
                ('hvac_system_type', models.CharField(blank=True, max_length=150, verbose_name='Central HVAC / Chiller Specification')),
                ('roof_type', models.CharField(blank=True, max_length=100, verbose_name='Roofing System (e.g. Built-Up Membrane, Metal)')),
                ('notes', models.TextField(blank=True, verbose_name='Facility Engineering Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_extension', to='assets.asset', verbose_name='Central Asset Record')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['building_id_code'],
            },
        ),
        migrations.CreateModel(
            name='BuildingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(default=1)),
                ('floor_name', models.CharField(blank=True, help_text='e.g. 2nd Floor Engineering Wing', max_length=100, null=True)),
                ('area_sqft', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_type', models.CharField(default='Office Space', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Building Floor',
                'verbose_name_plural': 'Building Floors',
                'ordering': ['floor_number'],
            },
        ),
    ]
