# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Budget Code / Ledger ID')),
                ('title', models.CharField(max_length=255, verbose_name='Budget Program Title')),
                ('budget_type', models.CharField(choices=[('ANNUAL_MASTER', 'Annual Master Operating Budget'), ('CAPITAL_PROJECT', 'Capital Infrastructure Project Fund'), ('MAINTENANCE_OPEX', 'Preventive & Corrective Maintenance OpEx'), ('DEPARTMENTAL', 'Departmental Operational Allocation'), ('EMERGENCY_RESERVE', 'Emergency Hazard Relief Fund')], default='MAINTENANCE_OPEX', max_length=50, verbose_name='Budget Classification')),
                ('fiscal_year', models.IntegerField(default=2026, verbose_name='Fiscal Year (FY)')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Total Allocated Amount ($)')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Total Incurred Expenditures ($)')),
                ('notes', models.TextField(blank=True, verbose_name='Fiscal Notes & Authorization Mandate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='organizations.department', verbose_name='Assigned Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.organization', verbose_name='Owner Agency')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets & Fiscal Allocations',
                'ordering': ['-fiscal_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Allocation Line / Category')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Budget Allocation Line',
                'verbose_name_plural': 'Budget Allocation Lines',
                'ordering': ['category_name'],
            },
        ),
    ]
