# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Official Asset Tag / ID')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('asset_type', models.CharField(choices=[('ROAD', 'Road / Highway Segment'), ('BRIDGE', 'Bridge / Overpass'), ('BUILDING', 'Building / Structure'), ('FACILITY', 'Facility / MEP Plant'), ('STREET_INFRA', 'Street & Traffic Infrastructure'), ('UTILITY', 'Power / Electrical Utility'), ('WATER', 'Water & Drainage Asset'), ('HEAVY_EQUIPMENT', 'Heavy Machinery & Fleet')], db_index=True, default='ROAD', max_length=50, verbose_name='Asset Classification')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation / Commissioning Date')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Initial Acquisition Cost ($)')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Current Book Value ($)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salvage / Residual Value ($)')),
                ('useful_life_years', models.IntegerField(default=25, verbose_name='Design Useful Life (Years)')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-Line Depreciation'), ('DECLINING_BALANCE', 'Double Declining Balance'), ('NONE', 'Non-Depreciating')], default='STRAIGHT_LINE', max_length=50, verbose_name='Depreciation Method')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent (90-100)'), ('GOOD', 'Good (70-89)'), ('FAIR', 'Fair (50-69)'), ('POOR', 'Poor (25-49)'), ('CRITICAL', 'Critical (0-24)')], db_index=True, default='GOOD', max_length=50, verbose_name='Condition Rating')),
                ('condition_score', models.IntegerField(default=85, verbose_name='Condition Score (0–100)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged / Impaired'), ('INACTIVE', 'Inactive / Standby'), ('RETIRED', 'Retired / Decommissioned')], db_index=True, default='ACTIVE', max_length=50, verbose_name='Operational Status')),
                ('lifecycle_stage', models.CharField(choices=[('PLANNING', '1. Planning & Design'), ('ACQUISITION', '2. Acquisition & Construction'), ('OPERATIONAL', '3. Active Operation'), ('MAINTENANCE', '4. Overhaul & Major Rehab'), ('RETIREMENT', '5. Retirement Assessment'), ('DECOMMISSIONED', '6. Decommissioned / Scrapped')], default='OPERATIONAL', max_length=50, verbose_name='Lifecycle Stage')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Warranty Expiration Date')),
                ('serial_number', models.CharField(blank=True, max_length=150, verbose_name='Manufacturer Serial Number')),
                ('barcode', models.CharField(blank=True, max_length=150, verbose_name='Barcode / RFID Identifier')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/%Y/%m/', verbose_name='Asset Photograph')),
                ('description', models.TextField(blank=True, verbose_name='Technical Description & Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organizations.department', verbose_name='Responsible Department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='locations.location', verbose_name='Geospatial Location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization', verbose_name='Owner Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assets', to=settings.AUTH_USER_MODEL, verbose_name='Custodian / Asset Manager')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('ACTIVE', 'Active / Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged / Impaired'), ('INACTIVE', 'Inactive / Standby'), ('RETIRED', 'Retired / Decommissioned')], max_length=50)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Active / Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged / Impaired'), ('INACTIVE', 'Inactive / Standby'), ('RETIRED', 'Retired / Decommissioned')], max_length=50)),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.asset', verbose_name='Asset')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Asset Status History',
                'verbose_name_plural': 'Asset Status History Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_id'], name='assets_asse_asset_i_501f65_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='assets_asse_asset_t_be4ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['condition_score'], name='assets_asse_conditi_cc829c_idx'),
        ),
    ]
