# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Contractor Company Legal Name')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Business License / Vendor ID')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Key Account Manager / Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Contact Phone')),
                ('address', models.TextField(verbose_name='Head Office Address')),
                ('specialization', models.CharField(choices=[('ASPHALT_PAVING', 'Highway Milling & Asphalt Paving'), ('BRIDGE_STRUCTURAL', 'Structural Steel & Bridge Rehabilitation'), ('MEP_HVAC', 'Mechanical, Electrical & HVAC Plant'), ('ELECTRICAL_GRID', 'High Voltage & Grid Utilities'), ('PLUMBING_WATER', 'Municipal Water Main & Storm Drainage'), ('TUNNEL_EARTHWORK', 'Excavation, Tunnels & Geotechnical'), ('GENERAL_CONSTRUCTION', 'General Civil Construction'), ('SECURITY_FIRE', 'Fire Suppression & Life Safety Systems')], default='GENERAL_CONSTRUCTION', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3, verbose_name='SLA Performance Rating (1.00-5.00)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Approved Vendor'), ('PROBATION', 'Probationary / Monitoring'), ('SUSPENDED', 'Suspended / Compliance Hold'), ('BLACKLISTED', 'Blacklisted / Disqualified'), ('INACTIVE', 'Inactive / Expired Agreement')], db_index=True, default='ACTIVE', max_length=30)),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Master Agreement Start Date')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Master Agreement Expiry Date')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='Commercial Liability Policy')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Insurance Expiration Date')),
                ('notes', models.TextField(blank=True, verbose_name='Vendor Qualifications & Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='organizations.organization', verbose_name='Primary Authorizing Agency')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=255, verbose_name='Contract Title')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Contract Reference Number')),
                ('total_contract_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Value ($)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_contracts', to='organizations.organization')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='contractors.contractor')),
            ],
            options={
                'verbose_name': 'Contract Agreement',
                'verbose_name_plural': 'Contract Agreements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('quality_score', models.IntegerField(default=4, verbose_name='Work Quality (1-5)')),
                ('safety_score', models.IntegerField(default=5, verbose_name='Safety & Compliance (1-5)')),
                ('timeliness_score', models.IntegerField(default=4, verbose_name='Timeliness & Milestones (1-5)')),
                ('overall_score', models.DecimalField(decimal_places=2, default=4.33, max_digits=3)),
                ('comments', models.TextField(blank=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='contractors.contractor')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractor Evaluation',
                'verbose_name_plural': 'Contractor Evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
