# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('ASSET_CHANGE', 'Asset State Changed'), ('MAINTENANCE_ACTION', 'Maintenance Executed'), ('PROJECT_CHANGE', 'Project Progress Updated'), ('BUDGET_ACTION', 'Budget Allocation/Expense'), ('PERMISSION_CHANGE', 'Permissions Modified'), ('DOCUMENT_ACTION', 'Document Upload/Download/Delete'), ('EXPORT', 'Data Exported'), ('SYSTEM', 'System Event')], db_index=True, default='SYSTEM', max_length=50, verbose_name='Action Performed')),
                ('module', models.CharField(db_index=True, max_length=100, verbose_name='System Module / App')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Object Display')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Field Changes (Diff)')),
                ('description', models.TextField(blank=True, verbose_name='Action Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent Browser')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor / User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['module', '-timestamp'], name='audit_audit_module_4e85d9_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
