# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warning_threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('critical_threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='%', max_length=30)),
                ('current_actual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_higher_better', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Target',
                'verbose_name_plural': 'KPI Targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('total_assets_count', models.PositiveIntegerField(default=0)),
                ('operational_assets_count', models.PositiveIntegerField(default=0)),
                ('under_repair_assets_count', models.PositiveIntegerField(default=0)),
                ('critical_defects_count', models.PositiveIntegerField(default=0)),
                ('active_workorders_count', models.PositiveIntegerField(default=0)),
                ('completed_inspections_count', models.PositiveIntegerField(default=0)),
                ('total_budget_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_budget_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('overall_health_index_avg', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Dashboard Metric Snapshot',
                'verbose_name_plural': 'Dashboard Metric Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureHealthIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pavement_condition_index', models.DecimalField(blank=True, decimal_places=2, help_text='PCI score (0 - 100)', max_digits=5, null=True)),
                ('bridge_condition_index', models.DecimalField(blank=True, decimal_places=2, help_text='BCI score (0 - 100)', max_digits=5, null=True)),
                ('structural_integrity_rating', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('risk_priority_number', models.PositiveIntegerField(default=1, help_text='RPN = Severity x Occurrence x Detection (1-1000)')),
                ('expected_remaining_service_life_years', models.DecimalField(decimal_places=1, default=Decimal('20.0'), max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_indexes', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Infrastructure Health Index',
                'verbose_name_plural': 'Infrastructure Health Indexes',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
