# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('module', models.CharField(choices=[('ASSETS', 'Asset Registry & Valuation'), ('WORKORDERS', 'Work Order Performance & Backlog'), ('INSPECTIONS', 'Condition & Inspection Audits'), ('FINANCIALS', 'Budget vs Actual Expenses'), ('CONTRACTORS', 'Contractor Performance & SLA'), ('INCIDENTS', 'Emergency Incidents & Response Logs'), ('INVENTORY', 'Stock Valuation & Consumption')], max_length=30)),
                ('default_format', models.CharField(choices=[('CSV', 'Comma-Separated Values (CSV)'), ('EXCEL', 'Microsoft Excel (XLSX)'), ('JSON', 'JSON Data Export'), ('PDF', 'PDF Document')], default='CSV', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['module', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('CSV', 'Comma-Separated Values (CSV)'), ('EXCEL', 'Microsoft Excel (XLSX)'), ('JSON', 'JSON Data Export'), ('PDF', 'PDF Document')], default='CSV', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Generation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file_size_kb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('execution_time_sec', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
