# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bridge_id_code', models.CharField(max_length=50, unique=True, verbose_name='Bridge Structure ID (NBI Code)')),
                ('bridge_name', models.CharField(max_length=255, verbose_name='Bridge Name / Feature Carried')),
                ('feature_crossed', models.CharField(max_length=200, verbose_name='Feature Intersected / Waterway / Canyon')),
                ('bridge_type', models.CharField(choices=[('PRESTRESSED_GIRDER', 'Prestressed Concrete Girder / Beam'), ('STEEL_TRUSS', 'Steel Truss Bridge'), ('SUSPENSION', 'Suspension Bridge'), ('CABLE_STAYED', 'Cable-Stayed Bridge'), ('CONCRETE_ARCH', 'Reinforced Concrete Arch'), ('STEEL_BOX_GIRDER', 'Steel Box Girder'), ('CANTILEVER', 'Cantilever Bridge'), ('CULVERT', 'Multi-Cell Box Culvert'), ('MOVABLE_DRAW', 'Movable / Bascule / Vertical Lift')], default='PRESTRESSED_GIRDER', max_length=50, verbose_name='Structural Type')),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Structure Length (Meters)')),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Deck Width Out-to-Out (Meters)')),
                ('span_count', models.IntegerField(default=1, verbose_name='Number of Main Spans')),
                ('main_span_length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maximum Span Length (Meters)')),
                ('construction_year', models.IntegerField(verbose_name='Original Year Built')),
                ('load_capacity_tons', models.DecimalField(decimal_places=2, default=40.0, max_digits=6, verbose_name='Design Live Load Capacity (Tons)')),
                ('vertical_clearance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Under-Clearance (Meters)')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent (NBI 9-8)'), ('GOOD', 'Good (NBI 7)'), ('FAIR', 'Fair (NBI 6-5)'), ('POOR', 'Poor (NBI 4)'), ('CRITICAL', 'Critical / Structurally Deficient (NBI 3-0)')], default='GOOD', max_length=50, verbose_name='Structural Condition Rating')),
                ('inspection_frequency_months', models.IntegerField(default=24, verbose_name='Mandatory Inspection Frequency (Months)')),
                ('is_scour_critical', models.BooleanField(default=False, verbose_name='Scour Critical Waterway Foundation')),
                ('notes', models.TextField(blank=True, verbose_name='Structural Engineering Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_extension', to='assets.asset', verbose_name='Central Asset Record')),
            ],
            options={
                'verbose_name': 'Bridge Structure',
                'verbose_name_plural': 'Bridge Structures',
                'ordering': ['bridge_id_code'],
            },
        ),
        migrations.CreateModel(
            name='BridgeComponentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('DECK', 'Bridge Deck & Wearing Surface'), ('SUPERSTRUCTURE', 'Superstructure Girders / Trusses'), ('SUBSTRUCTURE', 'Substructure Abutments & Piers'), ('BEARINGS', 'Elastomeric / Pot Bearings'), ('EXPANSION_JOINTS', 'Expansion Joints & Seals'), ('CULVERT_BARREL', 'Culvert Barrel / Headwalls'), ('SCOUR_PROTECTION', 'Riprap & Scour Countermeasures')], max_length=50)),
                ('rating_score_1_to_9', models.IntegerField(default=7, verbose_name='NBI Component Rating (1=Failed to 9=Excellent)')),
                ('findings', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bridges/components/%Y/%m/')),
                ('inspected_date', models.DateField()),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bridges.bridge')),
            ],
            options={
                'verbose_name': 'Bridge Component Inspection',
                'verbose_name_plural': 'Bridge Component Inspections',
                'ordering': ['-inspected_date'],
            },
        ),
    ]
