# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=50, verbose_name='Role Key')),
                ('module', models.CharField(choices=[('accounts', 'Accounts & Users'), ('organizations', 'Organizations & Hierarchy'), ('employees', 'Employees & Staff'), ('assets', 'Central Asset Registry'), ('roads', 'Road Infrastructure'), ('bridges', 'Bridge Infrastructure'), ('buildings', 'Building Infrastructure'), ('facilities', 'Facilities & MEP'), ('locations', 'Geospatial Locations & GIS'), ('inspections', 'Inspection Operations'), ('conditions', 'Condition Scoring & Curves'), ('maintenance', 'Maintenance Schedules & Plans'), ('workorders', 'Work Orders & Execution'), ('projects', 'Capital Projects & Gantt'), ('contractors', 'Contractors & Vendors'), ('budgets', 'Budgets & Fiscal Allocations'), ('expenses', 'Expense Tracking & Approvals'), ('incidents', 'Incident Management & Safety'), ('documents', 'Document Management System'), ('inventory', 'Maintenance Inventory & Spare Parts'), ('schedules', 'Recurring Scheduler'), ('notifications', 'Notification Hub'), ('analytics', 'Enterprise Analytics & KPIs'), ('reports', 'Reports & Data Exports'), ('support', 'Support Helpdesk & Complaints'), ('permissions', 'Security & Role Permissions'), ('audit', 'Audit Logs & Compliance')], db_index=True, max_length=50, verbose_name='Module Name')),
                ('can_view', models.BooleanField(default=True, verbose_name='Can View')),
                ('can_create', models.BooleanField(default=False, verbose_name='Can Create')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can Edit')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete')),
                ('can_approve', models.BooleanField(default=False, verbose_name='Can Approve')),
                ('can_export', models.BooleanField(default=False, verbose_name='Can Export Data')),
            ],
            options={
                'verbose_name': 'Role Permission Matrix Entry',
                'verbose_name_plural': 'Role Permission Matrix',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounts', 'Accounts & Users'), ('organizations', 'Organizations & Hierarchy'), ('employees', 'Employees & Staff'), ('assets', 'Central Asset Registry'), ('roads', 'Road Infrastructure'), ('bridges', 'Bridge Infrastructure'), ('buildings', 'Building Infrastructure'), ('facilities', 'Facilities & MEP'), ('locations', 'Geospatial Locations & GIS'), ('inspections', 'Inspection Operations'), ('conditions', 'Condition Scoring & Curves'), ('maintenance', 'Maintenance Schedules & Plans'), ('workorders', 'Work Orders & Execution'), ('projects', 'Capital Projects & Gantt'), ('contractors', 'Contractors & Vendors'), ('budgets', 'Budgets & Fiscal Allocations'), ('expenses', 'Expense Tracking & Approvals'), ('incidents', 'Incident Management & Safety'), ('documents', 'Document Management System'), ('inventory', 'Maintenance Inventory & Spare Parts'), ('schedules', 'Recurring Scheduler'), ('notifications', 'Notification Hub'), ('analytics', 'Enterprise Analytics & KPIs'), ('reports', 'Reports & Data Exports'), ('support', 'Support Helpdesk & Complaints'), ('permissions', 'Security & Role Permissions'), ('audit', 'Audit Logs & Compliance')], max_length=50, verbose_name='Module Name')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
            options={
                'verbose_name': 'User Permission Override',
                'verbose_name_plural': 'User Permission Overrides',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
