# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Certification / License Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Certification Code')),
                ('issuing_body', models.CharField(max_length=200, verbose_name='Issuing Regulatory Body')),
                ('validity_years', models.IntegerField(default=3, verbose_name='Validity Period (Years)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Job Designation Title')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Designation Code')),
                ('level', models.IntegerField(default=1, verbose_name='Hierarchy Level (1-10)')),
                ('pay_grade', models.CharField(blank=True, max_length=50, verbose_name='Pay Grade')),
                ('description', models.TextField(blank=True, verbose_name='Job Description & Requirements')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Skill Name')),
                ('category', models.CharField(choices=[('CIVIL', 'Civil & Structural Engineering'), ('ELECTRICAL', 'Electrical & Power Systems'), ('MECHANICAL', 'Mechanical & Heavy Plant'), ('GIS_SURVEY', 'GIS & Topographic Survey'), ('SAFETY', 'Occupational Health & Safety'), ('PROJECT_MGMT', 'Project & Contract Management'), ('INSPECTION', 'Quality & Non-Destructive Inspection')], default='CIVIL', max_length=50, verbose_name='Skill Category')),
                ('description', models.TextField(blank=True, verbose_name='Skill Description')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Official Employee ID')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time Permanent'), ('CONTRACT', 'Contractual / Project-Based'), ('CIVIL_SERVANT', 'Government / Civil Servant'), ('CONSULTANT', 'Technical Consultant'), ('INTERN', 'Apprentice / Trainee')], default='FULL_TIME', max_length=50, verbose_name='Employment Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / On Duty'), ('ON_LEAVE', 'On Approved Leave'), ('FIELD_ASSIGNMENT', 'On Remote Field Assignment'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated / Relieved'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=50, verbose_name='Employment Status')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency Contact Person')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Phone')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Compensation ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department', verbose_name='Department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='employees.designation', verbose_name='Job Designation')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.office', verbose_name='Base Office')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization', verbose_name='Organization')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='Direct Supervisor / Manager')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.team', verbose_name='Assigned Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Certificate / License Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/%Y/%m/', verbose_name='Certificate Document Copy')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Compliance / HR')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='employees.certification', verbose_name='Certification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Certification',
                'verbose_name_plural': 'Employee Certifications',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(choices=[(1, '1 - Novice / Basic Knowledge'), (2, '2 - Intermediate / Supervised Work'), (3, '3 - Competent / Independent Practitioner'), (4, '4 - Advanced / Lead Specialist'), (5, '5 - Expert / Master Authority')], default=3, verbose_name='Proficiency Level')),
                ('years_experience', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Years of Practical Experience')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee', verbose_name='Employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certified_employees', to='employees.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
