# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contractors', '0001_initial'),
        ('projects', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Expense Voucher Reference')),
                ('category', models.CharField(choices=[('LABOR', 'Field Engineering & Direct Labor'), ('MATERIALS', 'Paving / Structural Materials & Concrete'), ('EQUIPMENT', 'Heavy Machinery Rental & Fuel'), ('CONTRACTOR', 'Prime Contractor Progress Billing'), ('TRANSPORT', 'Logistics & Fleet Haulage'), ('EMERGENCY', 'Emergency Incident Response Action'), ('PERMITS', 'Environmental & Municipal Permits'), ('OTHER', 'Miscellaneous Expense')], default='MATERIALS', max_length=50, verbose_name='Expense Classification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Expense Amount ($)')),
                ('expense_date', models.DateField(verbose_name='Incurred Date')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Vendor Invoice / Bill No.')),
                ('description', models.TextField(verbose_name='Expense Summary & Line-Item Justification')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Invoice / Receipt Document')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Management Review'), ('APPROVED', 'Approved by Finance Officer'), ('REJECTED', 'Rejected / Disputed'), ('REIMBURSED', 'Reimbursed / Settled')], db_index=True, default='PENDING', max_length=50, verbose_name='Approval Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approving Authority')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='assets.asset', verbose_name='Target Asset')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='contractors.contractor', verbose_name='Vendor / Payee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project', verbose_name='Capital Project (Optional)')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workorders.workorder', verbose_name='Work Order (Optional)')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses & Invoices',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_id'], name='expenses_ex_expense_e1c5f7_idx'), models.Index(fields=['approval_status', '-expense_date'], name='expenses_ex_approva_d9d6d6_idx')],
            },
        ),
    ]
