# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contractors', '0001_initial'),
        ('inspections', '0001_initial'),
        ('organizations', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('PREVENTIVE_MAINTENANCE', 'Preventive Maintenance'), ('ROUTINE_INSPECTION', 'Routine Inspection'), ('STATUTORY_AUDIT', 'Statutory / Regulatory Audit'), ('STRUCTURAL_TESTING', 'Structural Non-Destructive Testing'), ('SEASONAL_PREPARATION', 'Monsoon / Winter Preparedness')], default='PREVENTIVE_MAINTENANCE', max_length=40)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 Months)'), ('BIANNUAL', 'Bi-Annual (6 Months)'), ('ANNUAL', 'Annual (1 Year)'), ('CUSTOM_DAYS', 'Custom Interval (Days)')], default='MONTHLY', max_length=30)),
                ('custom_interval_days', models.PositiveIntegerField(default=30, help_text='Used if frequency is Custom')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('last_performed_date', models.DateField(blank=True, null=True)),
                ('auto_generate_workorder', models.BooleanField(default=True, help_text='Automatically create Work Order upon trigger')),
                ('auto_generate_inspection', models.BooleanField(default=False, help_text='Automatically create Inspection upon trigger')),
                ('lead_time_days', models.PositiveIntegerField(default=3, help_text='Days prior to due date to create pending execution ticket')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='assets.asset')),
                ('assigned_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='contractors.contractor')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='organizations.team')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Asset Schedule',
                'verbose_name_plural': 'Asset Schedules',
                'ordering': ['next_due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEventExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped / Postponed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('findings_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedule_events', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='inspections.inspection')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='schedules.assetschedule')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Scheduled Event Execution',
                'verbose_name_plural': 'Scheduled Event Executions',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
