# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Organization Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Org Short Code')),
                ('org_type', models.CharField(choices=[('MUNICIPAL', 'Municipal Corporation'), ('HIGHWAY_AUTH', 'National / State Highway Authority'), ('PUBLIC_WORKS', 'Public Works Department (PWD)'), ('TRANSPORT', 'Transit & Transport Authority'), ('UTILITY', 'Water & Energy Utilities Authority'), ('PRIVATE_CONCESSIONAIRE', 'Private Infrastructure Concessionaire'), ('PORT_AIRPORT', 'Port & Aviation Authority')], default='PUBLIC_WORKS', max_length=50, verbose_name='Organization Type')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='Tax / Registration ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Official Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Helpline / Phone')),
                ('website', models.URLField(blank=True, verbose_name='Official Website')),
                ('address', models.TextField(blank=True, verbose_name='Headquarters Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Organization Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('annual_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Total Annual Budget ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, verbose_name='Department Code')),
                ('budget_allocation', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Allocated Annual Budget ($)')),
                ('description', models.TextField(blank=True, verbose_name='Description & Mandate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Head of Department (HOD)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Region Name')),
                ('code', models.CharField(max_length=50, verbose_name='Region Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='organizations.organization', verbose_name='Organization')),
                ('regional_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_regions', to=settings.AUTH_USER_MODEL, verbose_name='Regional Director / Head')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Office Name')),
                ('office_type', models.CharField(choices=[('HQ', 'Headquarters'), ('REGIONAL', 'Regional Directorate'), ('DIVISION', 'Division Office'), ('FIELD', 'Field Site Office'), ('WORKSHOP', 'Maintenance Depot / Workshop')], default='DIVISION', max_length=50, verbose_name='Office Type')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Office Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.organization', verbose_name='Organization')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='organizations.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Team Name')),
                ('code', models.CharField(max_length=50, verbose_name='Team Code')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization (e.g. Asphalt Paving, Structural NDT, HVAC)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.department', verbose_name='Parent Department')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organizations.office', verbose_name='Base Office')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Lead')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Zone Name')),
                ('code', models.CharField(max_length=50, verbose_name='Zone Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='organizations.region', verbose_name='Parent Region')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
                'unique_together': {('region', 'code')},
            },
        ),
    ]
