# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Incident Ticket Number')),
                ('title', models.CharField(max_length=255, verbose_name='Incident Title / Headline')),
                ('incident_type', models.CharField(choices=[('STRUCTURAL_DAMAGE', 'Structural Failure / Collapse Risk'), ('ROAD_HAZARD', 'Road Subsidence / Sinkhole / Severe Pothole'), ('EQUIPMENT_BREAKDOWN', 'Plant Equipment / Chiller / Lift Failure'), ('SAFETY_VIOLATION', 'Occupational Safety & Site Hazard'), ('ENVIRONMENTAL_SPILL', 'Chemical / Hazardous Material Spill'), ('FLOOD_WATERLOGGING', 'Severe Flooding & Stormwater Overflow'), ('POWER_OUTAGE', 'Substation Outage / Grid Fault'), ('CITIZEN_COMPLAINT', 'Citizen Public Works Grievance')], default='ROAD_HAZARD', max_length=50, verbose_name='Incident Classification')),
                ('severity', models.CharField(choices=[('LOW', 'Low (Informational / Non-Urgent)'), ('MEDIUM', 'Medium (Operational Impairment)'), ('HIGH', 'High (Imminent Safety Hazard)'), ('CRITICAL', 'Critical Disaster / Emergency Response')], db_index=True, default='HIGH', max_length=20, verbose_name='Severity Level')),
                ('description', models.TextField(verbose_name='Detailed Incident Narrative & Damage Description')),
                ('estimated_damage_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Estimated Damage / Repair Cost ($)')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported / Pending Triage'), ('DISPATCHED', 'Emergency Response Crew Dispatched'), ('UNDER_INVESTIGATION', 'Under On-Site Investigation'), ('CONTAINED', 'Hazard Contained / Safe'), ('RESOLVED', 'Fully Resolved & Repaired'), ('CLOSED', 'Closed & Archived')], db_index=True, default='REPORTED', max_length=50, verbose_name='Incident Status')),
                ('root_cause_analysis', models.TextField(blank=True, verbose_name='Root Cause Analysis (RCA)')),
                ('resolution_summary', models.TextField(blank=True, verbose_name='Corrective Action Resolution Summary')),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/', verbose_name='Incident Scene Photograph')),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='assets.asset', verbose_name='Impaired Infrastructure Asset')),
                ('emergency_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_incidents', to='organizations.team', verbose_name='Dispatched Emergency Response Team')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='locations.location', verbose_name='Geospatial Location')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Reporting Officer / Citizen')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents & Hazards',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.CharField(max_length=150, verbose_name='Responder / Officer Name')),
                ('action_taken', models.TextField(verbose_name='Containment Action Taken')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='incidents.incident', verbose_name='Incident Ticket')),
            ],
            options={
                'verbose_name': 'Incident Dispatch Log',
                'verbose_name_plural': 'Incident Dispatch Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_id'], name='incidents_i_inciden_c49d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity', '-reported_at'], name='incidents_i_status_5cf3ce_idx'),
        ),
    ]
