# Generated by Django 5.0.6 on 2026-09-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance Reminder'), ('WORKORDER', 'Work Order Notification'), ('INSPECTION', 'Inspection Alert'), ('INCIDENT', 'Emergency Incident Alert'), ('BUDGET', 'Budget Limit Threshold Alert'), ('INVENTORY', 'Low Stock Warning'), ('PROJECT', 'Project Deadline Milestone'), ('SUPPORT', 'Support Ticket Update'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Alert Title')),
                ('message', models.TextField(verbose_name='Notification Body')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Action URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender User (Optional)')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
